### ISSUE TITLE
Profile reports inconsistent

### ISSUE THREAD

**Issue by jczaplew** [naturalatlas/tilestrata#10]
When refreshed, the `/profile` endpoint seems to rotate between three different versions of statistics. To test, simply go to the `/profile` endpoint, make sure no requests are being made to the tile server, and refresh at least 3 times.

**Comment by brianreavis** [comment]
Hmm, that's really peculiar. I'll try to dig into it later today... in the meantime if you spot anything obvious, let me know!

**Comment by jczaplew** [comment]
Will do! I've been digging around a bit and nothing obvious sticks out. I'll continue poking though.

**Comment by jczaplew** [comment]
Oh wow, silly mistake - it was running in a cluster, so each response was from a different node. Sorry about that!
