### ISSUE TITLE
Possible to specify layers in extra file?

### ISSUE THREAD

**Issue by ge-fa** [naturalatlas/tilestrata#17]
Is it somehow and easy possible, to specify layers not directly in `index.js`, but instead in some other file(s), like `layer1.js`, `layer2.js`, `layerN.js` for example? This would ease the use of `puppet` or any other configuration management system.

I've used something like:

layer1.js:
```
strata.layer('layer1') 
[...]
module.exports = strata.layer('layer1');
```

index.js:
```
require('./layer1.js')
```

but this doesn't work, it leads to `404 Not Found`. 
(I've to admit, my knowledge regarding `nodejs` is really limited, but appreciate any pointers. Thanks!)

**Comment by brianreavis** [comment]
Yeah that's possible! The main thing you need to make sure to do is to share `strata` (the server instance from calling `tilestrata()`) between the two. The way I do it is:
```js
// index.js
var tilestrata = require('tilestrata');
var strata =  tilestrata();
require('./layer1.js')(strata);
strata.listen(port);

// layer1.js
module.exports = function(strata) {
    strata.layer('layer1')...
};
```

**Comment by ge-fa** [comment]
Thanks a lot!
