### ISSUE TITLE
Is it possible to serve tiles at {z}/{x}/{y}.{extension}?

### ISSUE THREAD

**Issue by chriswhong** [naturalatlas/tilestrata#20]
Tilestrata is great!  Just wondering if hosting tiles at `{z}/{x}/{y}.{extension}` is possible, or if the `/filename.png` at the end is always necessary.  Just trying to keep consistent URLs for map services I am setting up.

**Comment by jczaplew** [comment]
@brianreavis - would you be open to a pull request that optionally allows this URL format?

**Comment by brianreavis** [comment]
Now out in [2.1.0](https://github.com/naturalatlas/tilestrata/releases/tag/v2.1.0)!
