### ISSUE TITLE
could not create BreakIterator: U_MISSING_RESOURCE_ERROR

### ISSUE THREAD

**Issue by flfeeling2016** [naturalatlas/tilestrata#23]
when i use tilestrata,it gives me the erro:could not create BreakIterator: U_MISSING_RESOURCE_ERROR

**Comment by brianreavis** [comment]
This error isn't specific to tilestrata – it has to do with mapnik: https://github.com/mapnik/mapnik/issues/3193 (but I see you've discovered that [here](https://github.com/mapnik/node-mapnik/issues/827), so I'm going to close this issue)
