### ISSUE TITLE
Map extraction

### ISSUE THREAD

**Issue by carrbrpoa** [naturalatlas/tilestrata#24]
Hello,

Is it possible to request a "map extraction" based on a specific point?

Let's say I have a lat/long point and want to retrieve from Tilestrata a piece of map in a specific zoom level and with x pixels of width and y pixels of height.

If it's not ready, can I have some guideline on how to do it, or another suggestions? The goal is to store this piece of map and display it offline when needed, with a marker, preferably all together like an image.

**Comment by brandonreavis** [comment]
Have you checked out https://github.com/mapbox/abaculus? It will handle stitching tiles from any sort of tile server like tilestrata. For drawing things on top you can use something like https://github.com/Automattic/node-canvas.

**Comment by carrbrpoa** [comment]
Thanks Brandon, I'll check it out!

**Comment by carrbrpoa** [comment]
Awesome! Found a sample of extraction with abaculus and tile server here: https://github.com/mapbox/abaculus/issues/11#issuecomment-141427828

**Comment by carrbrpoa** [comment]
@brandonreavis Actually I tried with URL `'http://127.0.0.1:9999/basemap-custom-2/'+z+'/'+x+'/'+y+'.png';` and it throws `Error: image_reader: can't determine type from input data
    at Error (native)` in abaculus call, even showing the tiles URLs correctly in output, which works in browser. Any ideas?

**Comment by carrbrpoa** [comment]
Nevermind, it was a proxy issue.
