### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by VladimirKalachikhin** [naturalatlas/tilestrata#29]
Is there anyone who was able to run this? Last error:
```
stager@StagerServer:~/tilestrata/example$ node index.js 
/home/stager/node_modules/tilestrata/lib/TileRequestHandler.js:39
	if (this.provider) throw new Error('There is a provider already registered to this layer');
	                   ^

Error: There is a provider already registered to this layer
```
I broke down...

**Comment by brianreavis** [comment]
This error means there's a problem with your configuration (attempting to use two providers on a single layer). If you want more specific help, you'll need to post your layer configuration.

```js
strata.layer('basemap')
    .route('tile.png')
        .use(mapnik({ ... }))
        .use(mapnik({ ... })) // will trigger that error
```

**Comment by brianreavis** [comment]
Just noticed you were referencing the example that I forgot existed in the repository. The problem there was there was a small typo: 

https://github.com/naturalatlas/tilestrata/commit/0eacf8c393332a6aaa5c9c25da8eeae7786c4c8e#diff-f8c408fd257ff44ce4b01e5f8422b1e1R15
